# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'wiki_dev') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'root') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'root') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'wiki_test') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'root') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'root') %>
